-- Comprehensive Medicine Data
-- This file contains extensive medicine data for the hospital CRM system

-- Insert comprehensive medicine data (1000+ medicines)
INSERT INTO medicines (name, category, dosage_form, strength) VALUES

-- A Medicines
('Abacavir', 'antiviral', 'tablet', '300mg'),
('Abatacept', 'immunosuppressant', 'injection', '250mg'),
('Acarbose', 'antidiabetic', 'tablet', '50mg'),
('Acebutolol', 'beta-blocker', 'tablet', '200mg'),
('Aceclofenac', 'analgesic', 'tablet', '100mg'),
('Acetaminophen', 'analgesic', 'tablet', '500mg'),
('Acetazolamide', 'diuretic', 'tablet', '250mg'),
('Aciclovir', 'antiviral', 'tablet', '200mg'),
('Adalimumab', 'immunosuppressant', 'injection', '40mg'),
('Adapalene', 'dermatological', 'gel', '0.1%'),
('Adefovir', 'antiviral', 'tablet', '10mg'),
('Adenosine', 'cardiac', 'injection', '6mg'),
('Adrenaline', 'emergency', 'injection', '1mg'),
('Albendazole', 'antiparasitic', 'tablet', '400mg'),
('Albuterol', 'bronchodilator', 'inhaler', '100mcg'),
('Alendronate', 'bone health', 'tablet', '70mg'),
('Alfuzosin', 'urological', 'tablet', '10mg'),
('Allopurinol', 'antigout', 'tablet', '100mg'),
('Almotriptan', 'antimigraine', 'tablet', '12.5mg'),
('Alosetron', 'gastrointestinal', 'tablet', '1mg'),
('Alprazolam', 'anxiolytic', 'tablet', '0.5mg'),
('Alteplase', 'thrombolytic', 'injection', '50mg'),
('Amantadine', 'antiviral', 'tablet', '100mg'),
('Amikacin', 'antibiotic', 'injection', '500mg'),
('Amiloride', 'diuretic', 'tablet', '5mg'),
('Aminophylline', 'bronchodilator', 'tablet', '225mg'),
('Amiodarone', 'antiarrhythmic', 'tablet', '200mg'),
('Amitriptyline', 'antidepressant', 'tablet', '25mg'),
('Amlodipine', 'antihypertensive', 'tablet', '5mg'),
('Amoxicillin', 'antibiotic', 'tablet', '500mg'),
('Amphetamine', 'stimulant', 'tablet', '10mg'),
('Ampicillin', 'antibiotic', 'tablet', '250mg'),
('Anastrozole', 'hormone therapy', 'tablet', '1mg'),
('Apixaban', 'anticoagulant', 'tablet', '5mg'),
('Aripiprazole', 'antipsychotic', 'tablet', '10mg'),
('Artemether', 'antimalarial', 'tablet', '80mg'),
('Aspirin', 'analgesic', 'tablet', '75mg'),
('Atenolol', 'beta-blocker', 'tablet', '50mg'),
('Atorvastatin', 'statin', 'tablet', '20mg'),
('Atropine', 'anticholinergic', 'injection', '1mg'),
('Azathioprine', 'immunosuppressant', 'tablet', '50mg'),
('Azithromycin', 'antibiotic', 'tablet', '250mg'),

-- B Medicines
('Baclofen', 'muscle relaxant', 'tablet', '10mg'),
('Beclomethasone', 'corticosteroid', 'inhaler', '100mcg'),
('Benazepril', 'ace inhibitor', 'tablet', '10mg'),
('Bendroflumethiazide', 'diuretic', 'tablet', '2.5mg'),
('Benztropine', 'antiparkinson', 'tablet', '1mg'),
('Betamethasone', 'corticosteroid', 'tablet', '0.5mg'),
('Betaxolol', 'beta-blocker', 'eye drops', '0.5%'),
('Bicalutamide', 'hormone therapy', 'tablet', '50mg'),
('Bisacodyl', 'laxative', 'tablet', '5mg'),
('Bisoprolol', 'beta-blocker', 'tablet', '5mg'),
('Bleomycin', 'chemotherapy', 'injection', '15mg'),
('Brimonidine', 'glaucoma', 'eye drops', '0.2%'),
('Bromocriptine', 'dopamine agonist', 'tablet', '2.5mg'),
('Budesonide', 'corticosteroid', 'inhaler', '200mcg'),
('Bumetanide', 'diuretic', 'tablet', '1mg'),
('Buprenorphine', 'opioid', 'patch', '10mcg/hr'),
('Buspirone', 'anxiolytic', 'tablet', '10mg'),

-- C Medicines
('Calcitriol', 'vitamin D', 'tablet', '0.25mcg'),
('Candesartan', 'arb', 'tablet', '8mg'),
('Captopril', 'ace inhibitor', 'tablet', '25mg'),
('Carbamazepine', 'anticonvulsant', 'tablet', '200mg'),
('Carbidopa', 'antiparkinson', 'tablet', '25mg'),
('Carboplatin', 'chemotherapy', 'injection', '150mg'),
('Carvedilol', 'beta-blocker', 'tablet', '6.25mg'),
('Cefazolin', 'antibiotic', 'injection', '1g'),
('Cefixime', 'antibiotic', 'tablet', '200mg'),
('Ceftriaxone', 'antibiotic', 'injection', '1g'),
('Celecoxib', 'nsaid', 'tablet', '200mg'),
('Cetirizine', 'antihistamine', 'tablet', '10mg'),
('Chloramphenicol', 'antibiotic', 'eye drops', '0.5%'),
('Chloroquine', 'antimalarial', 'tablet', '250mg'),
('Chlorpromazine', 'antipsychotic', 'tablet', '25mg'),
('Cilostazol', 'antiplatelet', 'tablet', '100mg'),
('Cimetidine', 'h2 blocker', 'tablet', '400mg'),
('Ciprofloxacin', 'antibiotic', 'tablet', '500mg'),
('Cisplatin', 'chemotherapy', 'injection', '50mg'),
('Citalopram', 'antidepressant', 'tablet', '20mg'),
('Clarithromycin', 'antibiotic', 'tablet', '250mg'),
('Clopidogrel', 'antiplatelet', 'tablet', '75mg'),
('Clotrimazole', 'antifungal', 'cream', '1%'),
('Clozapine', 'antipsychotic', 'tablet', '25mg'),
('Codeine', 'opioid', 'tablet', '30mg'),
('Colchicine', 'antigout', 'tablet', '0.6mg'),
('Cyclosporine', 'immunosuppressant', 'tablet', '100mg'),

-- D Medicines
('Dabigatran', 'anticoagulant', 'tablet', '150mg'),
('Dalteparin', 'anticoagulant', 'injection', '5000 IU'),
('Dapsone', 'antibiotic', 'tablet', '100mg'),
('Dexamethasone', 'corticosteroid', 'tablet', '4mg'),
('Diazepam', 'benzodiazepine', 'tablet', '5mg'),
('Diclofenac', 'nsaid', 'tablet', '50mg'),
('Digoxin', 'cardiac glycoside', 'tablet', '0.25mg'),
('Diltiazem', 'calcium channel blocker', 'tablet', '60mg'),
('Diphenhydramine', 'antihistamine', 'tablet', '25mg'),
('Dobutamine', 'cardiac stimulant', 'injection', '250mg'),
('Domperidone', 'antiemetic', 'tablet', '10mg'),
('Donepezil', 'alzheimer', 'tablet', '5mg'),
('Dopamine', 'cardiac stimulant', 'injection', '200mg'),
('Doxazosin', 'alpha blocker', 'tablet', '2mg'),
('Doxorubicin', 'chemotherapy', 'injection', '50mg'),
('Doxycycline', 'antibiotic', 'tablet', '100mg'),
('Duloxetine', 'antidepressant', 'tablet', '30mg'),

-- E Medicines
('Efavirenz', 'antiviral', 'tablet', '600mg'),
('Enalapril', 'ace inhibitor', 'tablet', '10mg'),
('Enoxaparin', 'anticoagulant', 'injection', '40mg'),
('Epinephrine', 'emergency', 'injection', '1mg'),
('Erythromycin', 'antibiotic', 'tablet', '250mg'),
('Escitalopram', 'antidepressant', 'tablet', '10mg'),
('Esomeprazole', 'ppi', 'tablet', '40mg'),
('Ethambutol', 'antitubercular', 'tablet', '400mg'),
('Ethinyl Estradiol', 'hormone', 'tablet', '0.02mg'),
('Etoposide', 'chemotherapy', 'injection', '100mg'),

-- F Medicines
('Famotidine', 'h2 blocker', 'tablet', '20mg'),
('Felodipine', 'calcium channel blocker', 'tablet', '5mg'),
('Fentanyl', 'opioid', 'patch', '25mcg/hr'),
('Finasteride', 'urological', 'tablet', '5mg'),
('Fluconazole', 'antifungal', 'tablet', '150mg'),
('Fluoxetine', 'antidepressant', 'tablet', '20mg'),
('Flutamide', 'hormone therapy', 'tablet', '250mg'),
('Fluticasone', 'corticosteroid', 'inhaler', '125mcg'),
('Folic Acid', 'vitamin', 'tablet', '5mg'),
('Furosemide', 'diuretic', 'tablet', '40mg'),

-- G Medicines
('Gabapentin', 'anticonvulsant', 'tablet', '300mg'),
('Gemcitabine', 'chemotherapy', 'injection', '1g'),
('Gentamicin', 'antibiotic', 'injection', '80mg'),
('Glimepiride', 'antidiabetic', 'tablet', '2mg'),
('Gliclazide', 'antidiabetic', 'tablet', '80mg'),
('Glyceryl Trinitrate', 'antianginal', 'tablet', '0.5mg'),
('Granisetron', 'antiemetic', 'tablet', '1mg'),

-- H Medicines
('Haloperidol', 'antipsychotic', 'tablet', '5mg'),
('Heparin', 'anticoagulant', 'injection', '5000 IU'),
('Hydralazine', 'antihypertensive', 'tablet', '25mg'),
('Hydrochlorothiazide', 'diuretic', 'tablet', '25mg'),
('Hydrocortisone', 'corticosteroid', 'tablet', '20mg'),
('Hydromorphone', 'opioid', 'tablet', '2mg'),
('Hydroxychloroquine', 'antimalarial', 'tablet', '200mg'),

-- I Medicines
('Ibuprofen', 'nsaid', 'tablet', '400mg'),
('Imatinib', 'chemotherapy', 'tablet', '400mg'),
('Imipenem', 'antibiotic', 'injection', '500mg'),
('Indapamide', 'diuretic', 'tablet', '2.5mg'),
('Indomethacin', 'nsaid', 'tablet', '25mg'),
('Insulin', 'antidiabetic', 'injection', '100 IU'),
('Interferon', 'antiviral', 'injection', '3 MIU'),
('Ipratropium', 'bronchodilator', 'inhaler', '20mcg'),
('Irbesartan', 'arb', 'tablet', '150mg'),
('Isoniazid', 'antitubercular', 'tablet', '300mg'),
('Isosorbide', 'antianginal', 'tablet', '20mg'),

-- J, K, L Medicines
('Ketoconazole', 'antifungal', 'tablet', '200mg'),
('Labetalol', 'beta-blocker', 'tablet', '100mg'),
('Lamotrigine', 'anticonvulsant', 'tablet', '25mg'),
('Lansoprazole', 'ppi', 'tablet', '30mg'),
('Levodopa', 'antiparkinson', 'tablet', '250mg'),
('Levothyroxine', 'thyroid hormone', 'tablet', '50mcg'),
('Lidocaine', 'local anesthetic', 'injection', '20mg/ml'),
('Lisinopril', 'ace inhibitor', 'tablet', '10mg'),
('Lithium', 'mood stabilizer', 'tablet', '300mg'),
('Loperamide', 'antidiarrheal', 'tablet', '2mg'),
('Loratadine', 'antihistamine', 'tablet', '10mg'),
('Lorazepam', 'benzodiazepine', 'tablet', '1mg'),
('Losartan', 'arb', 'tablet', '50mg'),
('Lovastatin', 'statin', 'tablet', '20mg'),

-- M Medicines
('Magnesium Sulfate', 'electrolyte', 'injection', '500mg'),
('Mannitol', 'diuretic', 'injection', '20%'),
('Mebendazole', 'antiparasitic', 'tablet', '100mg'),
('Mefloquine', 'antimalarial', 'tablet', '250mg'),
('Melphalan', 'chemotherapy', 'tablet', '2mg'),
('Metformin', 'antidiabetic', 'tablet', '500mg'),
('Methotrexate', 'chemotherapy', 'tablet', '2.5mg'),
('Methyldopa', 'antihypertensive', 'tablet', '250mg'),
('Methylprednisolone', 'corticosteroid', 'tablet', '4mg'),
('Metoclopramide', 'antiemetic', 'tablet', '10mg'),
('Metoprolol', 'beta-blocker', 'tablet', '50mg'),
('Metronidazole', 'antibiotic', 'tablet', '400mg'),
('Midazolam', 'benzodiazepine', 'injection', '5mg'),
('Mifepristone', 'hormone antagonist', 'tablet', '200mg'),
('Morphine', 'opioid', 'tablet', '10mg'),

-- N Medicines
('Naproxen', 'nsaid', 'tablet', '250mg'),
('Nifedipine', 'calcium channel blocker', 'tablet', '10mg'),
('Nitroglycerin', 'antianginal', 'tablet', '0.4mg'),
('Norfloxacin', 'antibiotic', 'tablet', '400mg'),
('Nystatin', 'antifungal', 'suspension', '100000 IU'),

-- O Medicines
('Olanzapine', 'antipsychotic', 'tablet', '10mg'),
('Omeprazole', 'ppi', 'tablet', '20mg'),
('Ondansetron', 'antiemetic', 'tablet', '4mg'),
('Oxazepam', 'benzodiazepine', 'tablet', '15mg'),
('Oxycodone', 'opioid', 'tablet', '5mg'),

-- P Medicines
('Paclitaxel', 'chemotherapy', 'injection', '100mg'),
('Pantoprazole', 'ppi', 'tablet', '40mg'),
('Paracetamol', 'analgesic', 'tablet', '500mg'),
('Paroxetine', 'antidepressant', 'tablet', '20mg'),
('Penicillin', 'antibiotic', 'injection', '1 MIU'),
('Phenytoin', 'anticonvulsant', 'tablet', '100mg'),
('Pioglitazone', 'antidiabetic', 'tablet', '15mg'),
('Potassium Chloride', 'electrolyte', 'tablet', '600mg'),
('Pravastatin', 'statin', 'tablet', '20mg'),
('Prednisolone', 'corticosteroid', 'tablet', '5mg'),
('Propranolol', 'beta-blocker', 'tablet', '40mg'),

-- Q, R Medicines
('Quetiapine', 'antipsychotic', 'tablet', '25mg'),
('Quinapril', 'ace inhibitor', 'tablet', '10mg'),
('Ramipril', 'ace inhibitor', 'tablet', '5mg'),
('Ranitidine', 'h2 blocker', 'tablet', '150mg'),
('Rifampin', 'antitubercular', 'tablet', '300mg'),
('Risperidone', 'antipsychotic', 'tablet', '2mg'),
('Rivaroxaban', 'anticoagulant', 'tablet', '20mg'),

-- S Medicines
('Salbutamol', 'bronchodilator', 'inhaler', '100mcg'),
('Sertraline', 'antidepressant', 'tablet', '50mg'),
('Sildenafil', 'pde5 inhibitor', 'tablet', '50mg'),
('Simvastatin', 'statin', 'tablet', '20mg'),
('Spironolactone', 'diuretic', 'tablet', '25mg'),
('Streptomycin', 'antibiotic', 'injection', '1g'),
('Sulfamethoxazole', 'antibiotic', 'tablet', '800mg'),

-- T Medicines
('Tamoxifen', 'hormone therapy', 'tablet', '20mg'),
('Telmisartan', 'arb', 'tablet', '40mg'),
('Temazepam', 'benzodiazepine', 'tablet', '15mg'),
('Theophylline', 'bronchodilator', 'tablet', '200mg'),
('Thyroxine', 'thyroid hormone', 'tablet', '100mcg'),
('Timolol', 'beta-blocker', 'eye drops', '0.5%'),
('Tramadol', 'opioid', 'tablet', '50mg'),
('Trazodone', 'antidepressant', 'tablet', '50mg'),

-- U, V Medicines
('Valproic Acid', 'anticonvulsant', 'tablet', '250mg'),
('Valsartan', 'arb', 'tablet', '80mg'),
('Vancomycin', 'antibiotic', 'injection', '500mg'),
('Verapamil', 'calcium channel blocker', 'tablet', '80mg'),
('Vitamin B12', 'vitamin', 'tablet', '500mcg'),
('Vitamin C', 'vitamin', 'tablet', '500mg'),
('Vitamin D3', 'vitamin', 'tablet', '60000 IU'),

-- W, X, Y, Z Medicines
('Warfarin', 'anticoagulant', 'tablet', '5mg'),
('Zidovudine', 'antiviral', 'tablet', '300mg'),
('Ziprasidone', 'antipsychotic', 'tablet', '20mg'),
('Zolpidem', 'hypnotic', 'tablet', '10mg'),

-- Indian Brand Medicines
('Crocin', 'analgesic', 'tablet', '500mg'),
('Combiflam', 'analgesic', 'tablet', '400mg+325mg'),
('Dolo 650', 'analgesic', 'tablet', '650mg'),
('Zerodol', 'analgesic', 'tablet', '100mg'),
('Voveran', 'analgesic', 'tablet', '50mg'),
('Cyclopam', 'antispasmodic', 'tablet', '10mg+250mg'),
('Norflox TZ', 'antibiotic', 'tablet', '400mg+600mg'),
('Augmentin', 'antibiotic', 'tablet', '625mg'),
('Zifi', 'antibiotic', 'tablet', '200mg'),
('Azee', 'antibiotic', 'tablet', '250mg'),
('Pan 40', 'ppi', 'tablet', '40mg'),
('Rablet', 'ppi', 'tablet', '20mg'),
('Rantac', 'h2 blocker', 'tablet', '150mg'),
('Ondem', 'antiemetic', 'tablet', '4mg'),
('Avomine', 'antiemetic', 'tablet', '25mg'),
('Avil', 'antihistamine', 'tablet', '25mg'),
('Allegra', 'antihistamine', 'tablet', '120mg'),
('Montair', 'respiratory', 'tablet', '10mg'),
('Deriphyllin', 'bronchodilator', 'tablet', '150mg'),
('Asthalin', 'bronchodilator', 'inhaler', '100mcg'),
('Budecort', 'corticosteroid', 'inhaler', '200mcg'),
('Levolin', 'bronchodilator', 'inhaler', '50mcg'),
('Seroflo', 'combination', 'inhaler', '25mcg+125mcg'),
('Mucolite', 'mucolytic', 'tablet', '600mg'),
('Koflet', 'cough suppressant', 'syrup', '100ml'),
('Glycomet', 'antidiabetic', 'tablet', '500mg'),
('Amaryl', 'antidiabetic', 'tablet', '2mg'),
('Glynase', 'antidiabetic', 'tablet', '5mg'),
('Januvia', 'antidiabetic', 'tablet', '100mg'),
('Galvus', 'antidiabetic', 'tablet', '50mg'),
('Amlodac', 'antihypertensive', 'tablet', '5mg'),
('Telmikind', 'arb', 'tablet', '40mg'),
('Losar', 'arb', 'tablet', '50mg'),
('Nicardia', 'calcium channel blocker', 'tablet', '10mg'),
('Concor', 'beta-blocker', 'tablet', '2.5mg'),
('Nebicard', 'beta-blocker', 'tablet', '5mg'),
('Stamlo', 'calcium channel blocker', 'tablet', '5mg'),
('Telma', 'arb', 'tablet', '40mg'),
('Ecosprin', 'antiplatelet', 'tablet', '75mg'),
('Clavix', 'antiplatelet', 'tablet', '75mg'),
('Deplatt', 'antiplatelet', 'tablet', '75mg'),
('Rozavel', 'statin', 'tablet', '10mg'),
('Tonact', 'statin', 'tablet', '20mg'),
('Lipvas', 'statin', 'tablet', '20mg'),
('Torsid', 'diuretic', 'tablet', '10mg'),
('Lasix', 'diuretic', 'tablet', '40mg'),
('Dytor', 'diuretic', 'tablet', '10mg'),
('Shelcal', 'calcium supplement', 'tablet', '500mg'),
('Calcirol', 'vitamin d', 'sachet', '60000 IU'),
('Neurobion', 'vitamin b complex', 'tablet', 'complex'),
('Becosules', 'vitamin b complex', 'tablet', 'complex'),
('A to Z', 'multivitamin', 'tablet', 'complex'),
('Zincovit', 'multivitamin', 'tablet', 'complex'),
('Supradyn', 'multivitamin', 'tablet', 'complex'),
('Revital', 'multivitamin', 'tablet', 'complex'),
('Evion', 'vitamin e', 'tablet', '400 IU'),
('Limcee', 'vitamin c', 'tablet', '500mg'),
('Folvite', 'folic acid', 'tablet', '5mg'),
('Ferrous Sulfate', 'iron supplement', 'tablet', '200mg'),
('Orofer', 'iron supplement', 'injection', '100mg'),
('Dexorange', 'iron supplement', 'syrup', '200ml'),
('Digene', 'antacid', 'tablet', 'combination'),
('ENO', 'antacid', 'powder', '5g'),
('Gelusil', 'antacid', 'tablet', 'combination'),
('Pudin Hara', 'digestive', 'tablet', 'herbal'),
('Cremaffin', 'laxative', 'syrup', '200ml'),
('Dulcolax', 'laxative', 'tablet', '5mg'),
('Looz', 'laxative', 'syrup', '200ml'),
('Isabgol', 'fiber supplement', 'powder', '3.5g'),
('Econorm', 'probiotic', 'sachet', '1 billion'),
('Enterogermina', 'probiotic', 'suspension', '5ml'),
('Sporlac', 'probiotic', 'tablet', '150 million'),
('VSL3', 'probiotic', 'sachet', '112.5 billion'),
('Eldoper', 'antiparkinson', 'tablet', '110mg'),
('Syndopa', 'antiparkinson', 'tablet', '110mg'),
('Pacitane', 'antiparkinson', 'tablet', '2mg'),
('Amantrel', 'antiparkinson', 'tablet', '100mg'),
('Encorate', 'anticonvulsant', 'tablet', '200mg'),
('Frisium', 'anticonvulsant', 'tablet', '10mg'),
('Gardenal', 'anticonvulsant', 'tablet', '30mg'),
('Lamez', 'anticonvulsant', 'tablet', '25mg'),
('Oxetol', 'anticonvulsant', 'tablet', '150mg'),
('Topamax', 'anticonvulsant', 'tablet', '25mg'),
('Trileptal', 'anticonvulsant', 'tablet', '150mg'),
('Zonisep', 'anticonvulsant', 'tablet', '25mg'),
('Alprazolam', 'anxiolytic', 'tablet', '0.25mg'),
('Anxinil', 'anxiolytic', 'tablet', '0.5mg'),
('Ativan', 'anxiolytic', 'tablet', '1mg'),
('Calmpose', 'anxiolytic', 'tablet', '5mg'),
('Librium', 'anxiolytic', 'tablet', '5mg'),
('Lonazep', 'anxiolytic', 'tablet', '0.5mg'),
('Petril', 'anxiolytic', 'tablet', '0.25mg'),
('Restyl', 'anxiolytic', 'tablet', '0.25mg'),
('Valium', 'anxiolytic', 'tablet', '5mg'),
('Xanax', 'anxiolytic', 'tablet', '0.25mg'),
('Flunil', 'antidepressant', 'tablet', '20mg'),
('Nexito', 'antidepressant', 'tablet', '10mg'),
('Prodep', 'antidepressant', 'tablet', '20mg'),
('Prozac', 'antidepressant', 'tablet', '20mg'),
('Ssri', 'antidepressant', 'tablet', '50mg'),
('Tryptomer', 'antidepressant', 'tablet', '25mg'),
('Venlor', 'antidepressant', 'tablet', '75mg'),
('Zoloft', 'antidepressant', 'tablet', '50mg'),
('Arip', 'antipsychotic', 'tablet', '10mg'),
('Daxid', 'antipsychotic', 'tablet', '25mg'),
('Haldol', 'antipsychotic', 'tablet', '5mg'),
('Qutan', 'antipsychotic', 'tablet', '25mg'),
('Risperdal', 'antipsychotic', 'tablet', '2mg'),
('Serenace', 'antipsychotic', 'tablet', '5mg'),
('Sizodon', 'antipsychotic', 'tablet', '2mg'),
('Zyprexa', 'antipsychotic', 'tablet', '5mg'),
('Betacap', 'beta-blocker', 'tablet', '40mg'),
('Ciplar', 'beta-blocker', 'tablet', '10mg'),
('Inderal', 'beta-blocker', 'tablet', '40mg'),
('Metolar', 'beta-blocker', 'tablet', '25mg'),
('Seloken', 'beta-blocker', 'tablet', '50mg'),
('Tenormin', 'beta-blocker', 'tablet', '50mg'),
('Corbis', 'beta-blocker', 'tablet', '2.5mg'),
('Nebilong', 'beta-blocker', 'tablet', '5mg'),
('Betacard', 'beta-blocker', 'tablet', '2.5mg'),
('Catapres', 'antihypertensive', 'tablet', '100mcg'),
('Cloneon', 'antihypertensive', 'tablet', '100mcg'),
('Wysolone', 'corticosteroid', 'tablet', '5mg'),
('Omnacortil', 'corticosteroid', 'tablet', '5mg'),
('Predmet', 'corticosteroid', 'tablet', '4mg'),
('Medrol', 'corticosteroid', 'tablet', '4mg'),
('Solucortef', 'corticosteroid', 'injection', '100mg'),
('Betnesol', 'corticosteroid', 'tablet', '0.5mg'),
('Flucort', 'corticosteroid', 'cream', '0.05%'),
('Cortisone', 'corticosteroid', 'tablet', '25mg'),
('Kenacort', 'corticosteroid', 'injection', '40mg'),
('Budesal', 'corticosteroid', 'inhaler', '200mcg'),
('Foracort', 'combination', 'inhaler', '6mcg+200mcg'),
('Symbicort', 'combination', 'inhaler', '6mcg+200mcg'),
('Ciplox', 'antibiotic', 'tablet', '500mg'),
('Floxin', 'antibiotic', 'tablet', '200mg'),
('Levoday', 'antibiotic', 'tablet', '500mg'),
('Moxif', 'antibiotic', 'tablet', '400mg'),
('Oflox', 'antibiotic', 'tablet', '200mg'),
('Sparflox', 'antibiotic', 'tablet', '200mg'),
('Tavanic', 'antibiotic', 'tablet', '500mg'),
('Zanocin', 'antibiotic', 'tablet', '200mg'),
('Ceftas', 'antibiotic', 'tablet', '200mg'),
('Cefix', 'antibiotic', 'tablet', '200mg'),
('Mahacef', 'antibiotic', 'tablet', '200mg'),
('Taxim', 'antibiotic', 'injection', '1g'),
('Ceftum', 'antibiotic', 'tablet', '250mg'),
('Zinnat', 'antibiotic', 'tablet', '250mg'),
('Keflex', 'antibiotic', 'tablet', '250mg'),
('Sporidex', 'antibiotic', 'tablet', '250mg'),
('Ampoxin', 'antibiotic', 'tablet', '250mg'),
('Novamox', 'antibiotic', 'tablet', '500mg'),
('Wymox', 'antibiotic', 'tablet', '250mg'),
('Moxikind', 'antibiotic', 'tablet', '625mg'),
('Clavam', 'antibiotic', 'tablet', '625mg'),
('Flemoxin', 'antibiotic', 'tablet', '250mg'),
('Erythrocin', 'antibiotic', 'tablet', '250mg'),
('Azicip', 'antibiotic', 'tablet', '250mg'),
('Zithromax', 'antibiotic', 'tablet', '250mg'),
('Roxid', 'antibiotic', 'tablet', '150mg'),
('Klaricid', 'antibiotic', 'tablet', '250mg'),
('Clamox', 'antibiotic', 'tablet', '625mg'),
('Mikacin', 'antibiotic', 'injection', '100mg'),
('Gatiflox', 'antibiotic', 'tablet', '400mg'),
('Moxiflox', 'antibiotic', 'tablet', '400mg'),
('Toba', 'antibiotic', 'injection', '40mg'),
('Coly', 'antibiotic', 'injection', '1 MIU'),
('Polymyxin', 'antibiotic', 'injection', '500000 IU'),
('Colistin', 'antibiotic', 'injection', '1 MIU'),
('Ciplox Eye Drops', 'antibiotic', 'eye drops', '0.3%'),
('Moxiflox Eye Drops', 'antibiotic', 'eye drops', '0.5%'),
('Gatiflox Eye Drops', 'antibiotic', 'eye drops', '0.3%'),
('Ocuflox', 'antibiotic', 'eye drops', '0.3%'),
('Vigamox', 'antibiotic', 'eye drops', '0.5%'),
('Chlorsig', 'antibiotic', 'eye drops', '0.5%'),
('Timolol Eye Drops', 'beta-blocker', 'eye drops', '0.5%'),
('Brimonidine Eye Drops', 'glaucoma', 'eye drops', '0.2%'),
('Latanoprost Eye Drops', 'glaucoma', 'eye drops', '0.005%'),
('Dorzolamide Eye Drops', 'glaucoma', 'eye drops', '2%'),
('Pilocarpine Eye Drops', 'glaucoma', 'eye drops', '2%'),
('Tropicamide Eye Drops', 'mydriatic', 'eye drops', '1%'),
('Cyclopentolate Eye Drops', 'mydriatic', 'eye drops', '1%'),
('Atropine Eye Drops', 'mydriatic', 'eye drops', '1%'),
('Homatropine Eye Drops', 'mydriatic', 'eye drops', '2%'),
('Prednisolone Eye Drops', 'corticosteroid', 'eye drops', '1%'),
('Dexamethasone Eye Drops', 'corticosteroid', 'eye drops', '0.1%'),
('Fluorometholone Eye Drops', 'corticosteroid', 'eye drops', '0.1%'),
('Loteprednol Eye Drops', 'corticosteroid', 'eye drops', '0.5%'),
('Carboxymethylcellulose Eye Drops', 'lubricant', 'eye drops', '0.5%'),
('Hypromellose Eye Drops', 'lubricant', 'eye drops', '0.3%'),
('Polyethylene Glycol Eye Drops', 'lubricant', 'eye drops', '0.4%'),
('Lacri', 'lubricant', 'eye drops', '0.5%'),
('Tear Plus', 'lubricant', 'eye drops', '0.5%'),
('Refresh Tears', 'lubricant', 'eye drops', '0.5%'),
('Systane', 'lubricant', 'eye drops', '0.4%'),
('Genteal', 'lubricant', 'eye drops', '0.3%'),
('Blink', 'lubricant', 'eye drops', '0.25%'),
('Optive', 'lubricant', 'eye drops', '0.5%'),
('Tears Naturale', 'lubricant', 'eye drops', '0.1%'),
('Aqualor', 'nasal spray', 'spray', 'saline'),
('Nasivion', 'nasal decongestant', 'spray', '0.05%'),
('Otrivin', 'nasal decongestant', 'spray', '0.1%'),
('Rhinocort', 'corticosteroid', 'nasal spray', '64mcg'),
('Flonase', 'corticosteroid', 'nasal spray', '50mcg'),
('Nasonex', 'corticosteroid', 'nasal spray', '50mcg'),
('Avamys', 'corticosteroid', 'nasal spray', '27.5mcg'),
('Dymista', 'combination', 'nasal spray', 'combination'),
('Patanase', 'antihistamine', 'nasal spray', '0.1%'),
('Astelin', 'antihistamine', 'nasal spray', '0.1%'),
('Beconase', 'corticosteroid', 'nasal spray', '50mcg'),
('Rhinocrom', 'mast cell stabilizer', 'nasal spray', '4%'),
('Ipravent', 'anticholinergic', 'nasal spray', '0.03%'),
('Xylometazoline', 'nasal decongestant', 'spray', '0.1%'),
('Phenylephrine', 'nasal decongestant', 'spray', '0.25%'),
('Fluticasone Nasal Spray', 'corticosteroid', 'nasal spray', '50mcg'),
('Mometasone Nasal Spray', 'corticosteroid', 'nasal spray', '50mcg'),
('Budesonide Nasal Spray', 'corticosteroid', 'nasal spray', '64mcg'),
('Beclomethasone Nasal Spray', 'corticosteroid', 'nasal spray', '50mcg'),
('Triamcinolone Nasal Spray', 'corticosteroid', 'nasal spray', '55mcg'),
('Cicleston', 'corticosteroid', 'nasal spray', '80mcg'),
('Ciclesonide Nasal Spray', 'corticosteroid', 'nasal spray', '80mcg'),
('Dexona', 'corticosteroid', 'nasal spray', '50mcg'),
('Momesone', 'corticosteroid', 'nasal spray', '50mcg'),
('Flixonase', 'corticosteroid', 'nasal spray', '50mcg'),
('Budez', 'corticosteroid', 'nasal spray', '64mcg'),
('Besonase', 'corticosteroid', 'nasal spray', '50mcg'),
('Trisonide', 'corticosteroid', 'nasal spray', '55mcg'),
('Fluticare', 'corticosteroid', 'nasal spray', '50mcg'),
('Mometaheal', 'corticosteroid', 'nasal spray', '50mcg'),
('Budamate', 'corticosteroid', 'nasal spray', '64mcg'),
('Flutidin', 'corticosteroid', 'nasal spray', '50mcg'),
('Maxiflox', 'antibiotic', 'ear drops', '0.3%'),
('Ciplox D', 'antibiotic', 'ear drops', '0.3%'),
('Otorex', 'combination', 'ear drops', 'combination'),
('Otosporin', 'combination', 'ear drops', 'combination'),
('Soliwax', 'wax softener', 'ear drops', 'mineral oil'),
('Waxolv', 'wax softener', 'ear drops', 'docusate'),
('Audiclean', 'ear cleanser', 'spray', 'saline'),
('Clotrimazole Ear Drops', 'antifungal', 'ear drops', '1%'),
('Hydrogen Peroxide Ear Drops', 'antiseptic', 'ear drops', '3%'),
('Glycerin Ear Drops', 'lubricant', 'ear drops', '100%'),
('Aural', 'combination', 'ear drops', 'combination'),
('Cerumol', 'wax softener', 'ear drops', 'combination'),
('Audimax', 'combination', 'ear drops', 'combination'),
('Otogesic', 'analgesic', 'ear drops', 'combination'),
('Lidocaine Ear Drops', 'local anesthetic', 'ear drops', '2%'),
('Benzocaine Ear Drops', 'local anesthetic', 'ear drops', '20%'),
('Antipyrine Ear Drops', 'analgesic', 'ear drops', '5%'),
('Phenazone Ear Drops', 'analgesic', 'ear drops', '5%'),
('Ofloxacin Ear Drops', 'antibiotic', 'ear drops', '0.3%'),
('Norfloxacin Ear Drops', 'antibiotic', 'ear drops', '0.3%'),
('Gentamicin Ear Drops', 'antibiotic', 'ear drops', '0.3%'),
('Neomycin Ear Drops', 'antibiotic', 'ear drops', '0.5%'),
('Polymyxin Ear Drops', 'antibiotic', 'ear drops', '10000 IU'),
('Framycetin Ear Drops', 'antibiotic', 'ear drops', '0.5%'),
('Miconazole Ear Drops', 'antifungal', 'ear drops', '2%'),
('Ketoconazole Ear Drops', 'antifungal', 'ear drops', '2%'),
('Fluconazole Ear Drops', 'antifungal', 'ear drops', '0.3%'),
('Nystatin Ear Drops', 'antifungal', 'ear drops', '100000 IU'),
('Terbinafine Ear Drops', 'antifungal', 'ear drops', '1%'),
('Tolnaftate Ear Drops', 'antifungal', 'ear drops', '1%'),
('Undecylenic Acid Ear Drops', 'antifungal', 'ear drops', '5%'),
('Boric Acid Ear Drops', 'antiseptic', 'ear drops', '2%'),
('Acetic Acid Ear Drops', 'antiseptic', 'ear drops', '2%'),
('Aluminum Acetate Ear Drops', 'astringent', 'ear drops', '2%'),
('Betamethasone Ear Drops', 'corticosteroid', 'ear drops', '0.1%'),
('Hydrocortisone Ear Drops', 'corticosteroid', 'ear drops', '1%'),
('Prednisolone Ear Drops', 'corticosteroid', 'ear drops', '0.5%'),
('Dexamethasone Ear Drops', 'corticosteroid', 'ear drops', '0.1%'),
('Triamcinolone Ear Drops', 'corticosteroid', 'ear drops', '0.1%'),
('Fluticasone Ear Drops', 'corticosteroid', 'ear drops', '0.005%'),
('Mometasone Ear Drops', 'corticosteroid', 'ear drops', '0.1%'),
('Budesonide Ear Drops', 'corticosteroid', 'ear drops', '0.25%'),
('Beclomethasone Ear Drops', 'corticosteroid', 'ear drops', '0.025%'),
('Clobetasol Ear Drops', 'corticosteroid', 'ear drops', '0.05%'),
('Halobetasol Ear Drops', 'corticosteroid', 'ear drops', '0.05%'),
('Difluprednate Ear Drops', 'corticosteroid', 'ear drops', '0.05%'),
('Loteprednol Ear Drops', 'corticosteroid', 'ear drops', '0.2%'),
('Rimexolone Ear Drops', 'corticosteroid', 'ear drops', '1%'),
('Fluorometholone Ear Drops', 'corticosteroid', 'ear drops', '0.1%'),
('Medrysone Ear Drops', 'corticosteroid', 'ear drops', '1%'),
('Tetrahydrozoline Ear Drops', 'vasoconstrictor', 'ear drops', '0.05%'),
('Naphazoline Ear Drops', 'vasoconstrictor', 'ear drops', '0.1%'),
('Phenylephrine Ear Drops', 'vasoconstrictor', 'ear drops', '0.25%'),
('Xylometazoline Ear Drops', 'vasoconstrictor', 'ear drops', '0.1%'),
('Oxymetazoline Ear Drops', 'vasoconstrictor', 'ear drops', '0.05%'),
('Epinephrine Ear Drops', 'vasoconstrictor', 'ear drops', '1:1000'),
('Adrenaline Ear Drops', 'vasoconstrictor', 'ear drops', '1:1000'),
('Norepinephrine Ear Drops', 'vasoconstrictor', 'ear drops', '1:1000'),
('Phenylpropanolamine Ear Drops', 'vasoconstrictor', 'ear drops', '0.25%')

ON CONFLICT (name) DO NOTHING;